version: 0.0
os: linux
files:
  - source: /execute-deploy.sh
    destination: /home/ubuntu/zennbot-deploy
    overwrite: yes
  - source: /deploy.sh
    destination: /home/ubuntu/zennbot-deploy
    overwrite: yes
hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180