version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - ${HOME}/zennbot-docker/data/postgre:/var/lib/mongo/data