version: '3.0'

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - zennbot-network

  postgres:
    image: postgres
    volumes:
      - ${HOME}/zennbot-docker/data/postgres:/var/lib/postgres/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      zennbot-network:
        aliases:
          - zennbot-postgres
  
networks:
  zennbot-network: