version: '3.0'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-DEV
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.test
    networks:
      - zennbot-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres
    volumes:
      - ${HOME}/zennbot-docker/data/postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
    networks:
      zennbot-network:
        aliases:
          - zennbot-postgres

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    networks:
      zennbot-network:
        aliases:
          - zennbot-redis
  
networks:
  zennbot-network: