FROM node:16.13.2

ENV TZ=Asia/Seoul

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /usr/src/app
COPY prisma ./prisma/
COPY package.json ./
COPY yarn.lock ./

RUN yarn install
RUN yarn prisma:generate

COPY . .
