name: Check Branches

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependancy
      run: yarn

    - name: Run test
      run: docker compose -f docker-compose.test.yml run --rm web yarn test:e2e