name: Check Branches

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - uses: deptno/action-aws-ssm-to-dotenv@v1.3.1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-northeast-2
      with:
        ssm-path: /ZENNBOT/TEST
        output: .env.test
        decryption: true

    - uses: satackey/action-docker-layer-caching@v0.0.11

    - name: Build Docker
      run: docker compose -f docker-compose.test.yml build

    - name: Run test
      run: docker compose -f docker-compose.test.yml run --rm web yarn test:e2e