name: Check Branches

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependancy
      run: yarn

    - name: Run jest test
      run: yarn test
