name: Check Pull Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check:
    name: Check-PR
    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependancy
      run: yarn

    - name: Run test
      run: yarn test