name: Make Coverage

on:
  push:
    branches:
      - main

env:
  ECS_CLUSTER: zennbot-ecs
  ECS_SERVICE: image-deploy

jobs:
  coverage:
    name: Calculate Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependancy
      run: yarn

    - name: Run test and make coverage
      run: yarn test:ava:cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/coverage-final.json